package mocks

import mock "github.com/stretchr/testify/mock"
import openssl "github.com/mmcloughlin/openssl"

// PrivateKey is an autogenerated mock type for the PrivateKey type
type PrivateKey struct {
	mock.Mock
}

// MarshalPKCS1PrivateKeyDER provides a mock function with given fields:
func (_m *PrivateKey) MarshalPKCS1PrivateKeyDER() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarshalPKCS1PrivateKeyPEM provides a mock function with given fields:
func (_m *PrivateKey) MarshalPKCS1PrivateKeyPEM() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarshalPKCS1PublicKeyDER provides a mock function with given fields:
func (_m *PrivateKey) MarshalPKCS1PublicKeyDER() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarshalPKCS1PublicKeyPEM provides a mock function with given fields:
func (_m *PrivateKey) MarshalPKCS1PublicKeyPEM() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarshalPKIXPublicKeyDER provides a mock function with given fields:
func (_m *PrivateKey) MarshalPKIXPublicKeyDER() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarshalPKIXPublicKeyPEM provides a mock function with given fields:
func (_m *PrivateKey) MarshalPKIXPublicKeyPEM() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignPKCS1v15 provides a mock function with given fields: _a0, _a1
func (_m *PrivateKey) SignPKCS1v15(_a0 openssl.Method, _a1 []byte) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(openssl.Method, []byte) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(openssl.Method, []byte) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyPKCS1v15 provides a mock function with given fields: method, data, sig
func (_m *PrivateKey) VerifyPKCS1v15(method openssl.Method, data []byte, sig []byte) error {
	ret := _m.Called(method, data, sig)

	var r0 error
	if rf, ok := ret.Get(0).(func(openssl.Method, []byte, []byte) error); ok {
		r0 = rf(method, data, sig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// evpPKey provides a mock function with given fields:
func (_m *PrivateKey) evpPKey() *openssl._Ctype_struct_evp_pkey_st {
	ret := _m.Called()

	var r0 *openssl._Ctype_struct_evp_pkey_st
	if rf, ok := ret.Get(0).(func() *openssl._Ctype_struct_evp_pkey_st); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openssl._Ctype_struct_evp_pkey_st)
		}
	}

	return r0
}
