package mocks

import mock "github.com/stretchr/testify/mock"
import openssl "github.com/mmcloughlin/openssl"

// PublicKey is an autogenerated mock type for the PublicKey type
type PublicKey struct {
	mock.Mock
}

// MarshalPKCS1PublicKeyDER provides a mock function with given fields:
func (_m *PublicKey) MarshalPKCS1PublicKeyDER() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarshalPKCS1PublicKeyPEM provides a mock function with given fields:
func (_m *PublicKey) MarshalPKCS1PublicKeyPEM() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarshalPKIXPublicKeyDER provides a mock function with given fields:
func (_m *PublicKey) MarshalPKIXPublicKeyDER() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarshalPKIXPublicKeyPEM provides a mock function with given fields:
func (_m *PublicKey) MarshalPKIXPublicKeyPEM() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyPKCS1v15 provides a mock function with given fields: method, data, sig
func (_m *PublicKey) VerifyPKCS1v15(method openssl.Method, data []byte, sig []byte) error {
	ret := _m.Called(method, data, sig)

	var r0 error
	if rf, ok := ret.Get(0).(func(openssl.Method, []byte, []byte) error); ok {
		r0 = rf(method, data, sig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// evpPKey provides a mock function with given fields:
func (_m *PublicKey) evpPKey() *openssl._Ctype_struct_evp_pkey_st {
	ret := _m.Called()

	var r0 *openssl._Ctype_struct_evp_pkey_st
	if rf, ok := ret.Get(0).(func() *openssl._Ctype_struct_evp_pkey_st); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openssl._Ctype_struct_evp_pkey_st)
		}
	}

	return r0
}
