package mocks

import mock "github.com/stretchr/testify/mock"
import net "net"

// Pattern is an autogenerated mock type for the Pattern type
type Pattern struct {
	mock.Mock
}

// Describe provides a mock function with given fields:
func (_m *Pattern) Describe() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Matches provides a mock function with given fields: _a0, _a1
func (_m *Pattern) Matches(_a0 net.IP, _a1 uint16) bool {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(net.IP, uint16) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
